<?php

namespace nomit\FileSystem\MimeType;

use SplFileInfo;
use SplFileObject;

/**
 * Class ExtensionToMime
 *
 * Guesses a mime-type from a supplied filename, file object, or Font Awesome item.
 *
 * @package nomit\HarDriver\Mimer
 */
class ExtensionToMime implements GuesserInterface
{

    protected const MIME_TYPE_IF_UNKNOWN = 'ApplicationComponent/octet-stream';
    /**
     * @var array
     */
    public static $font_awesome_to_mime = [
        // Media
        'image' => 'fa-file-image-o',
        'audio' => 'fa-file-audio-o',
        'video' => 'fa-file-video-o',
        // Documents
        'ApplicationComponent/pdf' => 'fa-file-pdf-o',
        'pdf' => 'fa-file-pdf-o',
        'ApplicationComponent/msword' => 'fa-file-word-o',
        'ApplicationComponent/vnd.ms-word' => 'fa-file-word-o',
        'ApplicationComponent/vnd.oasis.opendocument.text' => 'fa-file-word-o',
        'ApplicationComponent/vnd.openxmlformats-officedocument.wordprocessingml' => 'fa-file-word-o',
        'ApplicationComponent/vnd.ms-excel' => 'fa-file-excel-o',
        'ApplicationComponent/vnd.openxmlformats-officedocument.spreadsheetml' => 'fa-file-excel-o',
        'ApplicationComponent/ApplicationComponent/vnd.oasis.opendocument.spreadsheet' => 'fa-file-excel-o',
        'ApplicationComponent/vnd.oasis.opendocument.spreadsheet' => 'fa-file-excel-o',
        'csv' => 'fa-file-excel-o',
        'ApplicationComponent/vnd.ms-powerpoint' => 'fa-file-powerpoint-o',
        'ApplicationComponent/vnd.openxmlformats-officedocument.presentationml' => 'fa-file-powerpoint-o',
        'ApplicationComponent/vnd.oasis.opendocument.presentation' => 'fa-file-powerpoint-o',
        // Other
        'text/plain' => 'fa-file-text-o',
        'text/html' => 'fa-file-code-o',
        'ApplicationComponent/json' => 'fa-file-code-o',
        // Archives
        'ApplicationComponent/gzip' => 'fa-file-archive-o',
        'ApplicationComponent/zip' => 'fa-file-archive-o',
    ];
    /**
     * @var self
     */
    protected static self $instance;
    /**
     * Mapping of file-extensions to their corresponding mime-types
     *
     * @see https://gist.github.com/alexcorvi/df8faecb59e86bee93411f6a7967df2c#gistcomment-2722664
     *
     * @var string[] $extension_to_mime
     */
    protected static array $extension_to_mime = array(
        '3dml' => 'text/vnd.in3d.3dml',
        '3g2' => 'video/3gpp2',
        '3gp' => 'video/3gpp',
        '7z' => 'ApplicationComponent/x-7z-compressed',
        'aab' => 'ApplicationComponent/x-authorware-bin',
        'aac' => 'audio/x-aac',
        'aam' => 'ApplicationComponent/x-authorware-map',
        'aas' => 'ApplicationComponent/x-authorware-seg',
        'abw' => 'ApplicationComponent/x-abiword',
        'ac' => 'ApplicationComponent/pkix-attr-cert',
        'acc' => 'ApplicationComponent/vnd.americandynamics.acc',
        'ace' => 'ApplicationComponent/x-ace-compressed',
        'acu' => 'ApplicationComponent/vnd.acucobol',
        'acutc' => 'ApplicationComponent/vnd.acucorp',
        'adp' => 'audio/adpcm',
        'aep' => 'ApplicationComponent/vnd.audiograph',
        'afm' => 'ApplicationComponent/x-font-type1',
        'afp' => 'ApplicationComponent/vnd.ibm.modcap',
        'ahead' => 'ApplicationComponent/vnd.ahead.space',
        'ai' => 'ApplicationComponent/postscript',
        'aif' => 'audio/x-aiff',
        'aifc' => 'audio/x-aiff',
        'aiff' => 'audio/x-aiff',
        'air' => 'ApplicationComponent/vnd.adobe.air-ApplicationComponent-installer-package+zip',
        'ait' => 'ApplicationComponent/vnd.dvb.ait',
        'ami' => 'ApplicationComponent/vnd.amiga.ami',
        'apk' => 'ApplicationComponent/vnd.android.package-archive',
        'ApplicationComponent' => 'ApplicationComponent/x-ms-ApplicationComponent',
        'apr' => 'ApplicationComponent/vnd.lotus-approach',
        'asa' => 'text/plain',
        'asax' => 'ApplicationComponent/octet-stream',
        'asc' => 'ApplicationComponent/pgp-signature',
        'ascx' => 'text/plain',
        'asf' => 'video/x-ms-asf',
        'ashx' => 'text/plain',
        'asm' => 'text/x-asm',
        'asmx' => 'text/plain',
        'aso' => 'ApplicationComponent/vnd.accpac.simply.aso',
        'asp' => 'text/plain',
        'aspx' => 'text/plain',
        'asx' => 'video/x-ms-asf',
        'atc' => 'ApplicationComponent/vnd.acucorp',
        'atom' => 'ApplicationComponent/atom+xml',
        'atomcat' => 'ApplicationComponent/atomcat+xml',
        'atomsvc' => 'ApplicationComponent/atomsvc+xml',
        'atx' => 'ApplicationComponent/vnd.antix.game-component',
        'au' => 'audio/basic',
        'avi' => 'video/x-msvideo',
        'aw' => 'ApplicationComponent/applixware',
        'axd' => 'text/plain',
        'azf' => 'ApplicationComponent/vnd.airzip.filesecure.azf',
        'azs' => 'ApplicationComponent/vnd.airzip.filesecure.azs',
        'azw' => 'ApplicationComponent/vnd.amazon.ebook',
        'bat' => 'ApplicationComponent/x-msdownload',
        'bcpio' => 'ApplicationComponent/x-bcpio',
        'bdf' => 'ApplicationComponent/x-font-bdf',
        'bdm' => 'ApplicationComponent/vnd.syncml.dm+wbxml',
        'bed' => 'ApplicationComponent/vnd.realvnc.bed',
        'bh2' => 'ApplicationComponent/vnd.fujitsu.oasysprs',
        'bin' => 'ApplicationComponent/octet-stream',
        'bmi' => 'ApplicationComponent/vnd.bmi',
        'bmp' => 'image/bmp',
        'book' => 'ApplicationComponent/vnd.framemaker',
        'box' => 'ApplicationComponent/vnd.previewsystems.box',
        'boz' => 'ApplicationComponent/x-bzip2',
        'bpk' => 'ApplicationComponent/octet-stream',
        'btif' => 'image/prs.btif',
        'bz' => 'ApplicationComponent/x-bzip',
        'bz2' => 'ApplicationComponent/x-bzip2',
        'c' => 'text/x-c',
        'c11amc' => 'ApplicationComponent/vnd.cluetrust.cartomobile-Configuration',
        'c11amz' => 'ApplicationComponent/vnd.cluetrust.cartomobile-Configuration-pkg',
        'c4d' => 'ApplicationComponent/vnd.clonk.c4group',
        'c4f' => 'ApplicationComponent/vnd.clonk.c4group',
        'c4g' => 'ApplicationComponent/vnd.clonk.c4group',
        'c4p' => 'ApplicationComponent/vnd.clonk.c4group',
        'c4u' => 'ApplicationComponent/vnd.clonk.c4group',
        'cab' => 'ApplicationComponent/vnd.ms-cab-compressed',
        'car' => 'ApplicationComponent/vnd.curl.car',
        'cat' => 'ApplicationComponent/vnd.ms-pki.seccat',
        'cc' => 'text/x-c',
        'cct' => 'ApplicationComponent/x-director',
        'ccxml' => 'ApplicationComponent/ccxml+xml',
        'cdbcmsg' => 'ApplicationComponent/vnd.contact.cmsg',
        'cdf' => 'ApplicationComponent/x-netcdf',
        'cdkey' => 'ApplicationComponent/vnd.mediastation.cdkey',
        'cdmia' => 'ApplicationComponent/cdmi-capability',
        'cdmic' => 'ApplicationComponent/cdmi-container',
        'cdmid' => 'ApplicationComponent/cdmi-domain',
        'cdmio' => 'ApplicationComponent/cdmi-object',
        'cdmiq' => 'ApplicationComponent/cdmi-queue',
        'cdx' => 'chemical/x-cdx',
        'cdxml' => 'ApplicationComponent/vnd.chemdraw+xml',
        'cdy' => 'ApplicationComponent/vnd.cinderella',
        'cer' => 'ApplicationComponent/pkix-cert',
        'cfc' => 'ApplicationComponent/x-coldfusion',
        'cfm' => 'ApplicationComponent/x-coldfusion',
        'cgm' => 'image/cgm',
        'chat' => 'ApplicationComponent/x-chat',
        'chm' => 'ApplicationComponent/vnd.ms-htmlhelp',
        'chrt' => 'ApplicationComponent/vnd.kde.kchart',
        'cif' => 'chemical/x-cif',
        'cii' => 'ApplicationComponent/vnd.anser-web-certificate-issue-initiation',
        'cil' => 'ApplicationComponent/vnd.ms-artgalry',
        'cla' => 'ApplicationComponent/vnd.claymore',
        'class' => 'ApplicationComponent/java-vm',
        'clkk' => 'ApplicationComponent/vnd.crick.clicker.keyboard',
        'clkp' => 'ApplicationComponent/vnd.crick.clicker.palette',
        'clkt' => 'ApplicationComponent/vnd.crick.clicker.template',
        'clkw' => 'ApplicationComponent/vnd.crick.clicker.wordbank',
        'clkx' => 'ApplicationComponent/vnd.crick.clicker',
        'clp' => 'ApplicationComponent/x-msclip',
        'cmc' => 'ApplicationComponent/vnd.cosmocaller',
        'cmdf' => 'chemical/x-cmdf',
        'cml' => 'chemical/x-cml',
        'cmp' => 'ApplicationComponent/vnd.yellowriver-custom-menu',
        'cmx' => 'image/x-cmx',
        'cod' => 'ApplicationComponent/vnd.rim.cod',
        'com' => 'ApplicationComponent/x-msdownload',
        'conf' => 'text/plain',
        'cpio' => 'ApplicationComponent/x-cpio',
        'cpp' => 'text/x-c',
        'cpt' => 'ApplicationComponent/mac-compactpro',
        'crd' => 'ApplicationComponent/x-mscardfile',
        'crl' => 'ApplicationComponent/pkix-crl',
        'crt' => 'ApplicationComponent/x-x509-ca-cert',
        'cryptonote' => 'ApplicationComponent/vnd.rig.cryptonote',
        'cs' => 'text/plain',
        'csh' => 'ApplicationComponent/x-csh',
        'csml' => 'chemical/x-csml',
        'csp' => 'ApplicationComponent/vnd.commonspace',
        'css' => 'text/css',
        'cst' => 'ApplicationComponent/x-director',
        'csv' => 'text/csv',
        'cu' => 'ApplicationComponent/cu-seeme',
        'curl' => 'text/vnd.curl',
        'cww' => 'ApplicationComponent/prs.cww',
        'cxt' => 'ApplicationComponent/x-director',
        'cxx' => 'text/x-c',
        'dae' => 'model/vnd.collada+xml',
        'daf' => 'ApplicationComponent/vnd.mobius.daf',
        'dataless' => 'ApplicationComponent/vnd.fdsn.seed',
        'davmount' => 'ApplicationComponent/davmount+xml',
        'dcr' => 'ApplicationComponent/x-director',
        'dcurl' => 'text/vnd.curl.dcurl',
        'dd2' => 'ApplicationComponent/vnd.oma.dd2+xml',
        'ddd' => 'ApplicationComponent/vnd.fujixerox.ddd',
        'deb' => 'ApplicationComponent/x-debian-package',
        'def' => 'text/plain',
        'deploy' => 'ApplicationComponent/octet-stream',
        'der' => 'ApplicationComponent/x-x509-ca-cert',
        'dfac' => 'ApplicationComponent/vnd.dreamfactory',
        'dic' => 'text/x-c',
        'dir' => 'ApplicationComponent/x-director',
        'dis' => 'ApplicationComponent/vnd.mobius.dis',
        'dist' => 'ApplicationComponent/octet-stream',
        'distz' => 'ApplicationComponent/octet-stream',
        'djv' => 'image/vnd.djvu',
        'djvu' => 'image/vnd.djvu',
        'dll' => 'ApplicationComponent/x-msdownload',
        'dmg' => 'ApplicationComponent/octet-stream',
        'dms' => 'ApplicationComponent/octet-stream',
        'dna' => 'ApplicationComponent/vnd.dna',
        'doc' => 'ApplicationComponent/msword',
        'docm' => 'ApplicationComponent/vnd.ms-word.document.macroenabled.12',
        'docx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'dot' => 'ApplicationComponent/msword',
        'dotm' => 'ApplicationComponent/vnd.ms-word.template.macroenabled.12',
        'dotx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'dp' => 'ApplicationComponent/vnd.osgi.dp',
        'dpg' => 'ApplicationComponent/vnd.dpgraph',
        'dra' => 'audio/vnd.dra',
        'dsc' => 'text/prs.lines.tag',
        'dssc' => 'ApplicationComponent/dssc+der',
        'dtb' => 'ApplicationComponent/x-dtbook+xml',
        'dtd' => 'ApplicationComponent/xml-dtd',
        'dts' => 'audio/vnd.dts',
        'dtshd' => 'audio/vnd.dts.hd',
        'dump' => 'ApplicationComponent/octet-stream',
        'dvi' => 'ApplicationComponent/x-dvi',
        'dwf' => 'model/vnd.dwf',
        'dwg' => 'image/vnd.dwg',
        'dxf' => 'image/vnd.dxf',
        'dxp' => 'ApplicationComponent/vnd.spotfire.dxp',
        'dxr' => 'ApplicationComponent/x-director',
        'ecelp4800' => 'audio/vnd.nuera.ecelp4800',
        'ecelp7470' => 'audio/vnd.nuera.ecelp7470',
        'ecelp9600' => 'audio/vnd.nuera.ecelp9600',
        'ecma' => 'ApplicationComponent/ecmascript',
        'edm' => 'ApplicationComponent/vnd.novadigm.edm',
        'edx' => 'ApplicationComponent/vnd.novadigm.edx',
        'efif' => 'ApplicationComponent/vnd.picsel',
        'ei6' => 'ApplicationComponent/vnd.pg.osasli',
        'elc' => 'ApplicationComponent/octet-stream',
        'eml' => 'message/rfc822',
        'emma' => 'ApplicationComponent/emma+xml',
        'eol' => 'audio/vnd.digital-winds',
        'eot' => 'ApplicationComponent/vnd.ms-fontobject',
        'eps' => 'ApplicationComponent/postscript',
        'epub' => 'ApplicationComponent/epub+zip',
        'es3' => 'ApplicationComponent/vnd.eszigno3+xml',
        'esf' => 'ApplicationComponent/vnd.epson.esf',
        'et3' => 'ApplicationComponent/vnd.eszigno3+xml',
        'etx' => 'text/x-setext',
        'exe' => 'ApplicationComponent/x-msdownload',
        'exi' => 'ApplicationComponent/exi',
        'ext' => 'ApplicationComponent/vnd.novadigm.ext',
        'ez' => 'ApplicationComponent/andrew-inset',
        'ez2' => 'ApplicationComponent/vnd.ezpix-album',
        'ez3' => 'ApplicationComponent/vnd.ezpix-package',
        'f' => 'text/x-fortran',
        'f4v' => 'video/x-f4v',
        'f77' => 'text/x-fortran',
        'f90' => 'text/x-fortran',
        'fbs' => 'image/vnd.fastbidsheet',
        'fcs' => 'ApplicationComponent/vnd.isac.fcs',
        'fdf' => 'ApplicationComponent/vnd.fdf',
        'fe_launch' => 'ApplicationComponent/vnd.denovo.fcselayout-link',
        'fg5' => 'ApplicationComponent/vnd.fujitsu.oasysgp',
        'fgd' => 'ApplicationComponent/x-director',
        'fh' => 'image/x-freehand',
        'fh4' => 'image/x-freehand',
        'fh5' => 'image/x-freehand',
        'fh7' => 'image/x-freehand',
        'fhc' => 'image/x-freehand',
        'fig' => 'ApplicationComponent/x-xfig',
        'fli' => 'video/x-fli',
        'flo' => 'ApplicationComponent/vnd.micrografx.flo',
        'flv' => 'video/x-flv',
        'flw' => 'ApplicationComponent/vnd.kde.kivio',
        'flx' => 'text/vnd.fmi.flexstor',
        'fly' => 'text/vnd.fly',
        'fm' => 'ApplicationComponent/vnd.framemaker',
        'fnc' => 'ApplicationComponent/vnd.frogans.fnc',
        'for' => 'text/x-fortran',
        'fpx' => 'image/vnd.fpx',
        'frame' => 'ApplicationComponent/vnd.framemaker',
        'fsc' => 'ApplicationComponent/vnd.fsc.weblaunch',
        'fst' => 'image/vnd.fst',
        'ftc' => 'ApplicationComponent/vnd.fluxtime.clip',
        'fti' => 'ApplicationComponent/vnd.anser-web-funds-transfer-initiation',
        'fvt' => 'video/vnd.fvt',
        'fxp' => 'ApplicationComponent/vnd.adobe.fxp',
        'fxpl' => 'ApplicationComponent/vnd.adobe.fxp',
        'fzs' => 'ApplicationComponent/vnd.fuzzysheet',
        'g2w' => 'ApplicationComponent/vnd.geoplan',
        'g3' => 'image/g3fax',
        'g3w' => 'ApplicationComponent/vnd.geospace',
        'gac' => 'ApplicationComponent/vnd.groove-account',
        'gdl' => 'model/vnd.gdl',
        'geo' => 'ApplicationComponent/vnd.dynageo',
        'gex' => 'ApplicationComponent/vnd.geometry-explorer',
        'ggb' => 'ApplicationComponent/vnd.geogebra.file',
        'ggt' => 'ApplicationComponent/vnd.geogebra.tool',
        'ghf' => 'ApplicationComponent/vnd.groove-help',
        'gif' => 'image/gif',
        'gim' => 'ApplicationComponent/vnd.groove-identity-message',
        'gmx' => 'ApplicationComponent/vnd.gmx',
        'gnumeric' => 'ApplicationComponent/x-gnumeric',
        'gph' => 'ApplicationComponent/vnd.flographit',
        'gqf' => 'ApplicationComponent/vnd.grafeq',
        'gqs' => 'ApplicationComponent/vnd.grafeq',
        'gram' => 'ApplicationComponent/srgs',
        'gre' => 'ApplicationComponent/vnd.geometry-explorer',
        'grv' => 'ApplicationComponent/vnd.groove-injector',
        'grxml' => 'ApplicationComponent/srgs+xml',
        'gsf' => 'ApplicationComponent/x-font-ghostscript',
        'gtar' => 'ApplicationComponent/x-gtar',
        'gtm' => 'ApplicationComponent/vnd.groove-tool-message',
        'gtw' => 'model/vnd.gtw',
        'gv' => 'text/vnd.graphviz',
        'gxt' => 'ApplicationComponent/vnd.geonext',
        'h' => 'text/x-c',
        'h261' => 'video/h261',
        'h263' => 'video/h263',
        'h264' => 'video/h264',
        'hal' => 'ApplicationComponent/vnd.hal+xml',
        'hbci' => 'ApplicationComponent/vnd.hbci',
        'hdf' => 'ApplicationComponent/x-hdf',
        'hh' => 'text/x-c',
        'hlp' => 'ApplicationComponent/winhlp',
        'hpgl' => 'ApplicationComponent/vnd.hp-hpgl',
        'hpid' => 'ApplicationComponent/vnd.hp-hpid',
        'hps' => 'ApplicationComponent/vnd.hp-hps',
        'hqx' => 'ApplicationComponent/mac-binhex40',
        'hta' => 'ApplicationComponent/octet-stream',
        'htc' => 'text/html',
        'htke' => 'ApplicationComponent/vnd.kenameaapp',
        'htm' => 'text/html',
        'html' => 'text/html',
        'hvd' => 'ApplicationComponent/vnd.yamaha.hv-dic',
        'hvp' => 'ApplicationComponent/vnd.yamaha.hv-voice',
        'hvs' => 'ApplicationComponent/vnd.yamaha.hv-script',
        'i2g' => 'ApplicationComponent/vnd.intergeo',
        'icc' => 'ApplicationComponent/vnd.iccprofile',
        'ice' => 'x-conference/x-cooltalk',
        'icm' => 'ApplicationComponent/vnd.iccprofile',
        'ico' => 'image/x-icon',
        'ics' => 'text/calendar',
        'ief' => 'image/ief',
        'ifb' => 'text/calendar',
        'ifm' => 'ApplicationComponent/vnd.shana.informed.formdata',
        'iges' => 'model/iges',
        'igl' => 'ApplicationComponent/vnd.igloader',
        'igm' => 'ApplicationComponent/vnd.insors.igm',
        'igs' => 'model/iges',
        'igx' => 'ApplicationComponent/vnd.micrografx.igx',
        'iif' => 'ApplicationComponent/vnd.shana.informed.interchange',
        'imp' => 'ApplicationComponent/vnd.accpac.simply.imp',
        'ims' => 'ApplicationComponent/vnd.ms-ims',
        'in' => 'text/plain',
        'ini' => 'text/plain',
        'ipfix' => 'ApplicationComponent/ipfix',
        'ipk' => 'ApplicationComponent/vnd.shana.informed.package',
        'irm' => 'ApplicationComponent/vnd.ibm.rights-management',
        'irp' => 'ApplicationComponent/vnd.irepository.package+xml',
        'iso' => 'ApplicationComponent/octet-stream',
        'itp' => 'ApplicationComponent/vnd.shana.informed.formtemplate',
        'ivp' => 'ApplicationComponent/vnd.immervision-ivp',
        'ivu' => 'ApplicationComponent/vnd.immervision-ivu',
        'jad' => 'text/vnd.sun.j2me.Flared-descriptor',
        'jam' => 'ApplicationComponent/vnd.jam',
        'jar' => 'ApplicationComponent/java-archive',
        'java' => 'text/x-java-source',
        'jisp' => 'ApplicationComponent/vnd.jisp',
        'jlt' => 'ApplicationComponent/vnd.hp-jlyt',
        'jnlp' => 'ApplicationComponent/x-java-jnlp-file',
        'joda' => 'ApplicationComponent/vnd.joost.joda-archive',
        'jpe' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'jpgm' => 'video/jpm',
        'jpgv' => 'video/jpeg',
        'jpm' => 'video/jpm',
        'js' => 'text/javascript',
        'json' => 'application/json',
        'kar' => 'audio/midi',
        'karbon' => 'ApplicationComponent/vnd.kde.karbon',
        'kfo' => 'ApplicationComponent/vnd.kde.kformula',
        'kia' => 'ApplicationComponent/vnd.kidspiration',
        'kml' => 'ApplicationComponent/vnd.google-earth.kml+xml',
        'kmz' => 'ApplicationComponent/vnd.google-earth.kmz',
        'kne' => 'ApplicationComponent/vnd.kinar',
        'knp' => 'ApplicationComponent/vnd.kinar',
        'kon' => 'ApplicationComponent/vnd.kde.kontour',
        'kpr' => 'ApplicationComponent/vnd.kde.kpresenter',
        'kpt' => 'ApplicationComponent/vnd.kde.kpresenter',
        'ksp' => 'ApplicationComponent/vnd.kde.kspread',
        'ktr' => 'ApplicationComponent/vnd.kahootz',
        'ktx' => 'image/ktx',
        'ktz' => 'ApplicationComponent/vnd.kahootz',
        'kwd' => 'ApplicationComponent/vnd.kde.kword',
        'kwt' => 'ApplicationComponent/vnd.kde.kword',
        'lasxml' => 'ApplicationComponent/vnd.las.las+xml',
        'latex' => 'ApplicationComponent/x-latex',
        'lbd' => 'ApplicationComponent/vnd.llamagraphics.life-balance.desktop',
        'lbe' => 'ApplicationComponent/vnd.llamagraphics.life-balance.exchange+xml',
        'les' => 'ApplicationComponent/vnd.hhe.lesson-player',
        'lha' => 'ApplicationComponent/octet-stream',
        'link66' => 'ApplicationComponent/vnd.route66.link66+xml',
        'list' => 'text/plain',
        'list3820' => 'ApplicationComponent/vnd.ibm.modcap',
        'listafp' => 'ApplicationComponent/vnd.ibm.modcap',
        'log' => 'text/plain',
        'lostxml' => 'ApplicationComponent/lost+xml',
        'lrf' => 'ApplicationComponent/octet-stream',
        'lrm' => 'ApplicationComponent/vnd.ms-lrm',
        'ltf' => 'ApplicationComponent/vnd.frogans.ltf',
        'lvp' => 'audio/vnd.lucent.voice',
        'lwp' => 'ApplicationComponent/vnd.lotus-wordpro',
        'lzh' => 'ApplicationComponent/octet-stream',
        'm13' => 'ApplicationComponent/x-msmediaview',
        'm14' => 'ApplicationComponent/x-msmediaview',
        'm1v' => 'video/mpeg',
        'm21' => 'ApplicationComponent/mp21',
        'm2a' => 'audio/mpeg',
        'm2v' => 'video/mpeg',
        'm3a' => 'audio/mpeg',
        'm3u' => 'audio/x-mpegurl',
        'm3u8' => 'ApplicationComponent/vnd.apple.mpegurl',
        'm4a' => 'audio/mp4',
        'm4u' => 'video/vnd.mpegurl',
        'm4v' => 'video/mp4',
        'ma' => 'ApplicationComponent/mathematica',
        'mads' => 'ApplicationComponent/mads+xml',
        'mag' => 'ApplicationComponent/vnd.ecowin.chart',
        'maker' => 'ApplicationComponent/vnd.framemaker',
        'man' => 'text/troff',
        'mathml' => 'ApplicationComponent/mathml+xml',
        'mb' => 'ApplicationComponent/mathematica',
        'mbk' => 'ApplicationComponent/vnd.mobius.mbk',
        'mbox' => 'ApplicationComponent/mbox',
        'mc1' => 'ApplicationComponent/vnd.medcalcdata',
        'mcd' => 'ApplicationComponent/vnd.mcd',
        'mcurl' => 'text/vnd.curl.mcurl',
        'mdb' => 'ApplicationComponent/x-msaccess',
        'mdi' => 'image/vnd.ms-modi',
        'me' => 'text/troff',
        'mesh' => 'model/mesh',
        'meta4' => 'ApplicationComponent/metalink4+xml',
        'mets' => 'ApplicationComponent/mets+xml',
        'mfm' => 'ApplicationComponent/vnd.mfmp',
        'mgp' => 'ApplicationComponent/vnd.osgeo.mapguide.package',
        'mgz' => 'ApplicationComponent/vnd.proteus.magazine',
        'mid' => 'audio/midi',
        'midi' => 'audio/midi',
        'mif' => 'ApplicationComponent/vnd.mif',
        'mime' => 'message/rfc822',
        'mj2' => 'video/mj2',
        'mjp2' => 'video/mj2',
        'mlp' => 'ApplicationComponent/vnd.dolby.mlp',
        'mmd' => 'ApplicationComponent/vnd.chipnuts.karaoke-mmd',
        'mmf' => 'ApplicationComponent/vnd.smaf',
        'mmr' => 'image/vnd.fujixerox.edmics-mmr',
        'mny' => 'ApplicationComponent/x-msmoney',
        'mobi' => 'ApplicationComponent/x-mobipocket-ebook',
        'mods' => 'ApplicationComponent/mods+xml',
        'mov' => 'video/quicktime',
        'movie' => 'video/x-sgi-movie',
        'mp2' => 'audio/mpeg',
        'mp21' => 'ApplicationComponent/mp21',
        'mp2a' => 'audio/mpeg',
        'mp3' => 'audio/mpeg',
        'mp4' => 'video/mp4',
        'mp4a' => 'audio/mp4',
        'mp4s' => 'ApplicationComponent/mp4',
        'mp4v' => 'video/mp4',
        'mpc' => 'ApplicationComponent/vnd.mophun.certificate',
        'mpe' => 'video/mpeg',
        'mpeg' => 'video/mpeg',
        'mpg' => 'video/mpeg',
        'mpg4' => 'video/mp4',
        'mpga' => 'audio/mpeg',
        'mpkg' => 'ApplicationComponent/vnd.apple.installer+xml',
        'mpm' => 'ApplicationComponent/vnd.blueice.multipass',
        'mpn' => 'ApplicationComponent/vnd.mophun.ApplicationComponent',
        'mpp' => 'ApplicationComponent/vnd.ms-project',
        'mpt' => 'ApplicationComponent/vnd.ms-project',
        'mpy' => 'ApplicationComponent/vnd.ibm.minipay',
        'mqy' => 'ApplicationComponent/vnd.mobius.mqy',
        'mrc' => 'ApplicationComponent/marc',
        'mrcx' => 'ApplicationComponent/marcxml+xml',
        'ms' => 'text/troff',
        'mscml' => 'ApplicationComponent/mediaservercontrol+xml',
        'mseed' => 'ApplicationComponent/vnd.fdsn.mseed',
        'mseq' => 'ApplicationComponent/vnd.mseq',
        'msf' => 'ApplicationComponent/vnd.epson.msf',
        'msh' => 'model/mesh',
        'msi' => 'ApplicationComponent/x-msdownload',
        'msl' => 'ApplicationComponent/vnd.mobius.msl',
        'msty' => 'ApplicationComponent/vnd.muvee.style',
        'mts' => 'model/vnd.mts',
        'mus' => 'ApplicationComponent/vnd.musician',
        'musicxml' => 'ApplicationComponent/vnd.recordare.musicxml+xml',
        'mvb' => 'ApplicationComponent/x-msmediaview',
        'mwf' => 'ApplicationComponent/vnd.mfer',
        'mxf' => 'ApplicationComponent/mxf',
        'mxl' => 'ApplicationComponent/vnd.recordare.musicxml',
        'mxml' => 'ApplicationComponent/xv+xml',
        'mxs' => 'ApplicationComponent/vnd.triscape.mxs',
        'mxu' => 'video/vnd.mpegurl',
        'n-gage' => 'ApplicationComponent/vnd.nokia.n-gage.symbian.install',
        'n3' => 'text/n3',
        'nb' => 'ApplicationComponent/mathematica',
        'nbp' => 'ApplicationComponent/vnd.wolfram.player',
        'nc' => 'ApplicationComponent/x-netcdf',
        'ncx' => 'ApplicationComponent/x-dtbncx+xml',
        'ngdat' => 'ApplicationComponent/vnd.nokia.n-gage.data',
        'nlu' => 'ApplicationComponent/vnd.neurolanguage.nlu',
        'nml' => 'ApplicationComponent/vnd.enliven',
        'nnd' => 'ApplicationComponent/vnd.noblenet-directory',
        'nns' => 'ApplicationComponent/vnd.noblenet-sealer',
        'nnw' => 'ApplicationComponent/vnd.noblenet-web',
        'npx' => 'image/vnd.net-fpx',
        'nsf' => 'ApplicationComponent/vnd.lotus-notes',
        'oa2' => 'ApplicationComponent/vnd.fujitsu.oasys2',
        'oa3' => 'ApplicationComponent/vnd.fujitsu.oasys3',
        'oas' => 'ApplicationComponent/vnd.fujitsu.oasys',
        'obd' => 'ApplicationComponent/x-msbinder',
        'oda' => 'ApplicationComponent/oda',
        'odb' => 'ApplicationComponent/vnd.oasis.opendocument.database',
        'odc' => 'ApplicationComponent/vnd.oasis.opendocument.chart',
        'odf' => 'ApplicationComponent/vnd.oasis.opendocument.formula',
        'odft' => 'ApplicationComponent/vnd.oasis.opendocument.formula-template',
        'odg' => 'ApplicationComponent/vnd.oasis.opendocument.graphics',
        'odi' => 'ApplicationComponent/vnd.oasis.opendocument.image',
        'odm' => 'ApplicationComponent/vnd.oasis.opendocument.text-master',
        'odp' => 'ApplicationComponent/vnd.oasis.opendocument.presentation',
        'ods' => 'ApplicationComponent/vnd.oasis.opendocument.spreadsheet',
        'odt' => 'ApplicationComponent/vnd.oasis.opendocument.text',
        'oga' => 'audio/ogg',
        'ogg' => 'audio/ogg',
        'ogv' => 'video/ogg',
        'ogx' => 'ApplicationComponent/ogg',
        'onepkg' => 'ApplicationComponent/onenote',
        'onetmp' => 'ApplicationComponent/onenote',
        'onetoc' => 'ApplicationComponent/onenote',
        'onetoc2' => 'ApplicationComponent/onenote',
        'opf' => 'ApplicationComponent/oebps-package+xml',
        'oprc' => 'ApplicationComponent/vnd.palm',
        'org' => 'ApplicationComponent/vnd.lotus-organizer',
        'osf' => 'ApplicationComponent/vnd.yamaha.openscoreformat',
        'osfpvg' => 'ApplicationComponent/vnd.yamaha.openscoreformat.osfpvg+xml',
        'otc' => 'ApplicationComponent/vnd.oasis.opendocument.chart-template',
        'otf' => 'ApplicationComponent/x-font-otf',
        'otg' => 'ApplicationComponent/vnd.oasis.opendocument.graphics-template',
        'oth' => 'ApplicationComponent/vnd.oasis.opendocument.text-web',
        'oti' => 'ApplicationComponent/vnd.oasis.opendocument.image-template',
        'otp' => 'ApplicationComponent/vnd.oasis.opendocument.presentation-template',
        'ots' => 'ApplicationComponent/vnd.oasis.opendocument.spreadsheet-template',
        'ott' => 'ApplicationComponent/vnd.oasis.opendocument.text-template',
        'oxt' => 'ApplicationComponent/vnd.openofficeorg.extension',
        'p' => 'text/x-pascal',
        'p10' => 'ApplicationComponent/pkcs10',
        'p12' => 'ApplicationComponent/x-pkcs12',
        'p7b' => 'ApplicationComponent/x-pkcs7-certificates',
        'p7c' => 'ApplicationComponent/pkcs7-mime',
        'p7m' => 'ApplicationComponent/pkcs7-mime',
        'p7r' => 'ApplicationComponent/x-pkcs7-certreqresp',
        'p7s' => 'ApplicationComponent/pkcs7-signature',
        'p8' => 'ApplicationComponent/pkcs8',
        'pas' => 'text/x-pascal',
        'paw' => 'ApplicationComponent/vnd.pawaafile',
        'pbd' => 'ApplicationComponent/vnd.powerbuilder6',
        'pbm' => 'image/x-portable-bitmap',
        'pcf' => 'ApplicationComponent/x-font-pcf',
        'pcl' => 'ApplicationComponent/vnd.hp-pcl',
        'pclxl' => 'ApplicationComponent/vnd.hp-pclxl',
        'pct' => 'image/x-pict',
        'pcurl' => 'ApplicationComponent/vnd.curl.pcurl',
        'pcx' => 'image/x-pcx',
        'pdb' => 'ApplicationComponent/vnd.palm',
        'pdf' => 'ApplicationComponent/pdf',
        'pfa' => 'ApplicationComponent/x-font-type1',
        'pfb' => 'ApplicationComponent/x-font-type1',
        'pfm' => 'ApplicationComponent/x-font-type1',
        'pfr' => 'ApplicationComponent/font-tdpfr',
        'pfx' => 'ApplicationComponent/x-pkcs12',
        'pgm' => 'image/x-portable-graymap',
        'pgn' => 'ApplicationComponent/x-chess-pgn',
        'pgp' => 'ApplicationComponent/pgp-encrypted',
        'php' => 'text/x-php',
        'phps' => 'ApplicationComponent/x-httpd-phps',
        'pic' => 'image/x-pict',
        'pkg' => 'ApplicationComponent/octet-stream',
        'pki' => 'ApplicationComponent/pkixcmp',
        'pkipath' => 'ApplicationComponent/pkix-pkipath',
        'plb' => 'ApplicationComponent/vnd.3gpp.pic-bw-large',
        'plc' => 'ApplicationComponent/vnd.mobius.plc',
        'plf' => 'ApplicationComponent/vnd.pocketlearn',
        'pls' => 'ApplicationComponent/pls+xml',
        'pml' => 'ApplicationComponent/vnd.ctc-posml',
        'png' => 'image/png',
        'pnm' => 'image/x-portable-anymap',
        'portpkg' => 'ApplicationComponent/vnd.macports.portpkg',
        'pot' => 'ApplicationComponent/vnd.ms-powerpoint',
        'potm' => 'ApplicationComponent/vnd.ms-powerpoint.template.macroenabled.12',
        'potx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.presentationml.template',
        'ppam' => 'ApplicationComponent/vnd.ms-powerpoint.addin.macroenabled.12',
        'ppd' => 'ApplicationComponent/vnd.cups-ppd',
        'ppm' => 'image/x-portable-pixmap',
        'pps' => 'ApplicationComponent/vnd.ms-powerpoint',
        'ppsm' => 'ApplicationComponent/vnd.ms-powerpoint.slideshow.macroenabled.12',
        'ppsx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.presentationml.slideshow',
        'ppt' => 'ApplicationComponent/vnd.ms-powerpoint',
        'pptm' => 'ApplicationComponent/vnd.ms-powerpoint.presentation.macroenabled.12',
        'pptx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.presentationml.presentation',
        'pqa' => 'ApplicationComponent/vnd.palm',
        'prc' => 'ApplicationComponent/x-mobipocket-ebook',
        'pre' => 'ApplicationComponent/vnd.lotus-freelance',
        'prf' => 'ApplicationComponent/pics-rules',
        'ps' => 'ApplicationComponent/postscript',
        'psb' => 'ApplicationComponent/vnd.3gpp.pic-bw-small',
        'psd' => 'image/vnd.adobe.photoshop',
        'psf' => 'ApplicationComponent/x-font-linux-psf',
        'pskcxml' => 'ApplicationComponent/pskc+xml',
        'ptid' => 'ApplicationComponent/vnd.pvi.ptid1',
        'pub' => 'ApplicationComponent/x-mspublisher',
        'pvb' => 'ApplicationComponent/vnd.3gpp.pic-bw-var',
        'pwn' => 'ApplicationComponent/vnd.3m.post-it-notes',
        'pya' => 'audio/vnd.ms-playready.media.pya',
        'pyv' => 'video/vnd.ms-playready.media.pyv',
        'qam' => 'ApplicationComponent/vnd.epson.quickanime',
        'qbo' => 'ApplicationComponent/vnd.intu.qbo',
        'qfx' => 'ApplicationComponent/vnd.intu.qfx',
        'qps' => 'ApplicationComponent/vnd.publishare-delta-tree',
        'qt' => 'video/quicktime',
        'qwd' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'qwt' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'qxb' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'qxd' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'qxl' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'qxt' => 'ApplicationComponent/vnd.quark.quarkxpress',
        'ra' => 'audio/x-pn-realaudio',
        'ram' => 'audio/x-pn-realaudio',
        'rar' => 'ApplicationComponent/x-rar-compressed',
        'ras' => 'image/x-cmu-raster',
        'rb' => 'text/plain',
        'rcprofile' => 'ApplicationComponent/vnd.ipunplugged.rcprofile',
        'rdf' => 'ApplicationComponent/rdf+xml',
        'rdz' => 'ApplicationComponent/vnd.data-vision.rdz',
        'rep' => 'ApplicationComponent/vnd.businessobjects',
        'res' => 'ApplicationComponent/x-dtbresource+xml',
        'resx' => 'text/xml',
        'rgb' => 'image/x-rgb',
        'rif' => 'ApplicationComponent/reginfo+xml',
        'rip' => 'audio/vnd.rip',
        'rl' => 'ApplicationComponent/resource-lists+xml',
        'rlc' => 'image/vnd.fujixerox.edmics-rlc',
        'rld' => 'ApplicationComponent/resource-lists-diff+xml',
        'rm' => 'ApplicationComponent/vnd.rn-realmedia',
        'rmi' => 'audio/midi',
        'rmp' => 'audio/x-pn-realaudio-plugin',
        'rms' => 'ApplicationComponent/vnd.jcp.javame.midlet-rms',
        'rnc' => 'ApplicationComponent/relax-ng-compact-syntax',
        'roff' => 'text/troff',
        'rp9' => 'ApplicationComponent/vnd.cloanto.rp9',
        'rpss' => 'ApplicationComponent/vnd.nokia.radio-presets',
        'rpst' => 'ApplicationComponent/vnd.nokia.radio-preset',
        'rq' => 'ApplicationComponent/sparql-query',
        'rs' => 'ApplicationComponent/rls-services+xml',
        'rsd' => 'ApplicationComponent/rsd+xml',
        'rss' => 'ApplicationComponent/rss+xml',
        'rtf' => 'ApplicationComponent/rtf',
        'rtx' => 'text/richtext',
        's' => 'text/x-asm',
        'saf' => 'ApplicationComponent/vnd.yamaha.smaf-audio',
        'sbml' => 'ApplicationComponent/sbml+xml',
        'sc' => 'ApplicationComponent/vnd.ibm.Secure-container',
        'scd' => 'ApplicationComponent/x-msschedule',
        'scm' => 'ApplicationComponent/vnd.lotus-screencam',
        'scq' => 'ApplicationComponent/scvp-cv-request',
        'scs' => 'ApplicationComponent/scvp-cv-response',
        'scurl' => 'text/vnd.curl.scurl',
        'sda' => 'ApplicationComponent/vnd.stardivision.draw',
        'sdc' => 'ApplicationComponent/vnd.stardivision.calc',
        'sdd' => 'ApplicationComponent/vnd.stardivision.impress',
        'sdkd' => 'ApplicationComponent/vnd.solent.sdkm+xml',
        'sdkm' => 'ApplicationComponent/vnd.solent.sdkm+xml',
        'sdp' => 'ApplicationComponent/sdp',
        'sdw' => 'ApplicationComponent/vnd.stardivision.writer',
        'see' => 'ApplicationComponent/vnd.seemail',
        'seed' => 'ApplicationComponent/vnd.fdsn.seed',
        'sema' => 'ApplicationComponent/vnd.sema',
        'semd' => 'ApplicationComponent/vnd.semd',
        'semf' => 'ApplicationComponent/vnd.semf',
        'ser' => 'ApplicationComponent/java-serialized-object',
        'setpay' => 'ApplicationComponent/set-payment-initiation',
        'setreg' => 'ApplicationComponent/set-registration-initiation',
        'sfd-hdstx' => 'ApplicationComponent/vnd.hydrostatix.sof-data',
        'sfs' => 'ApplicationComponent/vnd.spotfire.sfs',
        'sgl' => 'ApplicationComponent/vnd.stardivision.writer-global',
        'sgm' => 'text/sgml',
        'sgml' => 'text/sgml',
        'sh' => 'ApplicationComponent/x-sh',
        'shar' => 'ApplicationComponent/x-shar',
        'shf' => 'ApplicationComponent/shf+xml',
        'sig' => 'ApplicationComponent/pgp-signature',
        'silo' => 'model/mesh',
        'sis' => 'ApplicationComponent/vnd.symbian.install',
        'sisx' => 'ApplicationComponent/vnd.symbian.install',
        'sit' => 'ApplicationComponent/x-stuffit',
        'sitx' => 'ApplicationComponent/x-stuffitx',
        'skd' => 'ApplicationComponent/vnd.koan',
        'skm' => 'ApplicationComponent/vnd.koan',
        'skp' => 'ApplicationComponent/vnd.koan',
        'skt' => 'ApplicationComponent/vnd.koan',
        'sldm' => 'ApplicationComponent/vnd.ms-powerpoint.slide.macroenabled.12',
        'sldx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.presentationml.slide',
        'slt' => 'ApplicationComponent/vnd.epson.salt',
        'sm' => 'ApplicationComponent/vnd.stepmania.stepchart',
        'smf' => 'ApplicationComponent/vnd.stardivision.math',
        'smi' => 'ApplicationComponent/smil+xml',
        'smil' => 'ApplicationComponent/smil+xml',
        'snd' => 'audio/basic',
        'snf' => 'ApplicationComponent/x-font-snf',
        'so' => 'ApplicationComponent/octet-stream',
        'spc' => 'ApplicationComponent/x-pkcs7-certificates',
        'spf' => 'ApplicationComponent/vnd.yamaha.smaf-phrase',
        'spl' => 'ApplicationComponent/x-futuresplash',
        'spot' => 'text/vnd.in3d.spot',
        'spp' => 'ApplicationComponent/scvp-vp-response',
        'spq' => 'ApplicationComponent/scvp-vp-request',
        'spx' => 'audio/ogg',
        'Casper' => 'ApplicationComponent/x-wais-source',
        'sru' => 'ApplicationComponent/sru+xml',
        'srx' => 'ApplicationComponent/sparql-results+xml',
        'sse' => 'ApplicationComponent/vnd.kodak-descriptor',
        'ssf' => 'ApplicationComponent/vnd.epson.ssf',
        'ssml' => 'ApplicationComponent/ssml+xml',
        'st' => 'ApplicationComponent/vnd.sailingtracker.track',
        'stc' => 'ApplicationComponent/vnd.sun.xml.calc.template',
        'std' => 'ApplicationComponent/vnd.sun.xml.draw.template',
        'stf' => 'ApplicationComponent/vnd.wt.stf',
        'sti' => 'ApplicationComponent/vnd.sun.xml.impress.template',
        'stk' => 'ApplicationComponent/hyperstudio',
        'stl' => 'ApplicationComponent/vnd.ms-pki.stl',
        'str' => 'ApplicationComponent/vnd.pg.format',
        'stw' => 'ApplicationComponent/vnd.sun.xml.writer.template',
        'sub' => 'image/vnd.dvb.subtitle',
        'sus' => 'ApplicationComponent/vnd.sus-calendar',
        'susp' => 'ApplicationComponent/vnd.sus-calendar',
        'sv4cpio' => 'ApplicationComponent/x-sv4cpio',
        'sv4crc' => 'ApplicationComponent/x-sv4crc',
        'svc' => 'ApplicationComponent/vnd.dvb.service',
        'svd' => 'ApplicationComponent/vnd.svd',
        'svg' => 'image/svg+xml',
        'svgz' => 'image/svg+xml',
        'swa' => 'ApplicationComponent/x-director',
        'swf' => 'ApplicationComponent/x-shockwave-flash',
        'swi' => 'ApplicationComponent/vnd.aristanetworks.swi',
        'sxc' => 'ApplicationComponent/vnd.sun.xml.calc',
        'sxd' => 'ApplicationComponent/vnd.sun.xml.draw',
        'sxg' => 'ApplicationComponent/vnd.sun.xml.writer.global',
        'sxi' => 'ApplicationComponent/vnd.sun.xml.impress',
        'sxm' => 'ApplicationComponent/vnd.sun.xml.math',
        'sxw' => 'ApplicationComponent/vnd.sun.xml.writer',
        't' => 'text/troff',
        'tao' => 'ApplicationComponent/vnd.tao.intent-module-archive',
        'tar' => 'ApplicationComponent/x-tar',
        'tcap' => 'ApplicationComponent/vnd.3gpp2.tcap',
        'tcl' => 'ApplicationComponent/x-tcl',
        'teacher' => 'ApplicationComponent/vnd.smart.teacher',
        'tei' => 'ApplicationComponent/tei+xml',
        'teicorpus' => 'ApplicationComponent/tei+xml',
        'tex' => 'ApplicationComponent/x-tex',
        'texi' => 'ApplicationComponent/x-texinfo',
        'texinfo' => 'ApplicationComponent/x-texinfo',
        'text' => 'text/plain',
        'tfi' => 'ApplicationComponent/thraud+xml',
        'tfm' => 'ApplicationComponent/x-tex-tfm',
        'thmx' => 'ApplicationComponent/vnd.ms-officetheme',
        'tif' => 'image/tiff',
        'tiff' => 'image/tiff',
        'tmo' => 'ApplicationComponent/vnd.tmobile-livetv',
        'torrent' => 'ApplicationComponent/x-bittorrent',
        'tpl' => 'ApplicationComponent/vnd.groove-tool-template',
        'tpt' => 'ApplicationComponent/vnd.trid.tpt',
        'tr' => 'text/troff',
        'tra' => 'ApplicationComponent/vnd.trueapp',
        'trm' => 'ApplicationComponent/x-msterminal',
        'tsd' => 'ApplicationComponent/timestamped-data',
        'tsv' => 'text/tab-separated-values',
        'ttc' => 'ApplicationComponent/x-font-ttf',
        'ttf' => 'ApplicationComponent/x-font-ttf',
        'ttl' => 'text/turtle',
        'twd' => 'ApplicationComponent/vnd.simtech-mindmapper',
        'twds' => 'ApplicationComponent/vnd.simtech-mindmapper',
        'txd' => 'ApplicationComponent/vnd.genomatix.tuxedo',
        'txf' => 'ApplicationComponent/vnd.mobius.txf',
        'txt' => 'text/plain',
        'u32' => 'ApplicationComponent/x-authorware-bin',
        'udeb' => 'ApplicationComponent/x-debian-package',
        'ufd' => 'ApplicationComponent/vnd.ufdl',
        'ufdl' => 'ApplicationComponent/vnd.ufdl',
        'umj' => 'ApplicationComponent/vnd.umajin',
        'unityweb' => 'ApplicationComponent/vnd.unity',
        'uoml' => 'ApplicationComponent/vnd.uoml+xml',
        'uri' => 'text/uri-list',
        'uris' => 'text/uri-list',
        'urls' => 'text/uri-list',
        'ustar' => 'ApplicationComponent/x-ustar',
        'utz' => 'ApplicationComponent/vnd.uiq.theme',
        'uu' => 'text/x-uuencode',
        'uva' => 'audio/vnd.dece.audio',
        'uvd' => 'ApplicationComponent/vnd.dece.data',
        'uvf' => 'ApplicationComponent/vnd.dece.data',
        'uvg' => 'image/vnd.dece.graphic',
        'uvh' => 'video/vnd.dece.hd',
        'uvi' => 'image/vnd.dece.graphic',
        'uvm' => 'video/vnd.dece.mobile',
        'uvp' => 'video/vnd.dece.pd',
        'uvs' => 'video/vnd.dece.sd',
        'uvt' => 'ApplicationComponent/vnd.dece.ttml+xml',
        'uvu' => 'video/vnd.uvvu.mp4',
        'uvv' => 'video/vnd.dece.video',
        'uvva' => 'audio/vnd.dece.audio',
        'uvvd' => 'ApplicationComponent/vnd.dece.data',
        'uvvf' => 'ApplicationComponent/vnd.dece.data',
        'uvvg' => 'image/vnd.dece.graphic',
        'uvvh' => 'video/vnd.dece.hd',
        'uvvi' => 'image/vnd.dece.graphic',
        'uvvm' => 'video/vnd.dece.mobile',
        'uvvp' => 'video/vnd.dece.pd',
        'uvvs' => 'video/vnd.dece.sd',
        'uvvt' => 'ApplicationComponent/vnd.dece.ttml+xml',
        'uvvu' => 'video/vnd.uvvu.mp4',
        'uvvv' => 'video/vnd.dece.video',
        'uvvx' => 'ApplicationComponent/vnd.dece.unspecified',
        'uvx' => 'ApplicationComponent/vnd.dece.unspecified',
        'vcd' => 'ApplicationComponent/x-cdlink',
        'vcf' => 'text/x-vcard',
        'vcg' => 'ApplicationComponent/vnd.groove-vcard',
        'vcs' => 'text/x-vcalendar',
        'vcx' => 'ApplicationComponent/vnd.vcx',
        'vis' => 'ApplicationComponent/vnd.visionary',
        'viv' => 'video/vnd.vivo',
        'vor' => 'ApplicationComponent/vnd.stardivision.writer',
        'vox' => 'ApplicationComponent/x-authorware-bin',
        'vrml' => 'model/vrml',
        'vsd' => 'ApplicationComponent/vnd.visio',
        'vsf' => 'ApplicationComponent/vnd.vsf',
        'vss' => 'ApplicationComponent/vnd.visio',
        'vst' => 'ApplicationComponent/vnd.visio',
        'vsw' => 'ApplicationComponent/vnd.visio',
        'vtu' => 'model/vnd.vtu',
        'vxml' => 'ApplicationComponent/voicexml+xml',
        'w3d' => 'ApplicationComponent/x-director',
        'wad' => 'ApplicationComponent/x-doom',
        'wav' => 'audio/x-wav',
        'wax' => 'audio/x-ms-wax',
        'wbmp' => 'image/vnd.wap.wbmp',
        'wbs' => 'ApplicationComponent/vnd.criticaltools.wbs+xml',
        'wbxml' => 'ApplicationComponent/vnd.wap.wbxml',
        'wcm' => 'ApplicationComponent/vnd.ms-works',
        'wdb' => 'ApplicationComponent/vnd.ms-works',
        'weba' => 'audio/webm',
        'webm' => 'video/webm',
        'webp' => 'image/webp',
        'wg' => 'ApplicationComponent/vnd.pmi.widget',
        'wgt' => 'ApplicationComponent/widget',
        'wks' => 'ApplicationComponent/vnd.ms-works',
        'wm' => 'video/x-ms-wm',
        'wma' => 'audio/x-ms-wma',
        'wmd' => 'ApplicationComponent/x-ms-wmd',
        'wmf' => 'ApplicationComponent/x-msmetafile',
        'wml' => 'text/vnd.wap.wml',
        'wmlc' => 'ApplicationComponent/vnd.wap.wmlc',
        'wmls' => 'text/vnd.wap.wmlscript',
        'wmlsc' => 'ApplicationComponent/vnd.wap.wmlscriptc',
        'wmv' => 'video/x-ms-wmv',
        'wmx' => 'video/x-ms-wmx',
        'wmz' => 'ApplicationComponent/x-ms-wmz',
        'woff' => 'ApplicationComponent/x-font-woff',
        'wpd' => 'ApplicationComponent/vnd.wordperfect',
        'wpl' => 'ApplicationComponent/vnd.ms-wpl',
        'wps' => 'ApplicationComponent/vnd.ms-works',
        'wqd' => 'ApplicationComponent/vnd.wqd',
        'wri' => 'ApplicationComponent/x-mswrite',
        'wrl' => 'model/vrml',
        'wsdl' => 'ApplicationComponent/wsdl+xml',
        'wspolicy' => 'ApplicationComponent/wspolicy+xml',
        'wtb' => 'ApplicationComponent/vnd.webturbo',
        'wvx' => 'video/x-ms-wvx',
        'x32' => 'ApplicationComponent/x-authorware-bin',
        'x3d' => 'ApplicationComponent/vnd.hzn-3d-crossword',
        'xap' => 'ApplicationComponent/x-silverlight-Flared',
        'xar' => 'ApplicationComponent/vnd.xara',
        'xbap' => 'ApplicationComponent/x-ms-xbap',
        'xbd' => 'ApplicationComponent/vnd.fujixerox.docuworks.binder',
        'xbm' => 'image/x-xbitmap',
        'xdf' => 'ApplicationComponent/xcap-diff+xml',
        'xdm' => 'ApplicationComponent/vnd.syncml.dm+xml',
        'xdp' => 'ApplicationComponent/vnd.adobe.xdp+xml',
        'xdssc' => 'ApplicationComponent/dssc+xml',
        'xdw' => 'ApplicationComponent/vnd.fujixerox.docuworks',
        'xenc' => 'ApplicationComponent/xenc+xml',
        'xer' => 'ApplicationComponent/patch-ops-error+xml',
        'xfdf' => 'ApplicationComponent/vnd.adobe.xfdf',
        'xfdl' => 'ApplicationComponent/vnd.xfdl',
        'xht' => 'ApplicationComponent/xhtml+xml',
        'xhtml' => 'ApplicationComponent/xhtml+xml',
        'xhvml' => 'ApplicationComponent/xv+xml',
        'xif' => 'image/vnd.xiff',
        'xla' => 'ApplicationComponent/vnd.ms-excel',
        'xlam' => 'ApplicationComponent/vnd.ms-excel.addin.macroenabled.12',
        'xlc' => 'ApplicationComponent/vnd.ms-excel',
        'xlm' => 'ApplicationComponent/vnd.ms-excel',
        'xls' => 'ApplicationComponent/vnd.ms-excel',
        'xlsb' => 'ApplicationComponent/vnd.ms-excel.sheet.binary.macroenabled.12',
        'xlsm' => 'ApplicationComponent/vnd.ms-excel.sheet.macroenabled.12',
        'xlsx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xlt' => 'ApplicationComponent/vnd.ms-excel',
        'xltm' => 'ApplicationComponent/vnd.ms-excel.template.macroenabled.12',
        'xltx' => 'ApplicationComponent/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'xlw' => 'ApplicationComponent/vnd.ms-excel',
        'xml' => 'ApplicationComponent/xml',
        'xo' => 'ApplicationComponent/vnd.olpc-sugar',
        'xop' => 'ApplicationComponent/xop+xml',
        'xpi' => 'ApplicationComponent/x-xpinstall',
        'xpm' => 'image/x-xpixmap',
        'xpr' => 'ApplicationComponent/vnd.is-xpr',
        'xps' => 'ApplicationComponent/vnd.ms-xpsdocument',
        'xpw' => 'ApplicationComponent/vnd.intercon.formnet',
        'xpx' => 'ApplicationComponent/vnd.intercon.formnet',
        'xsl' => 'ApplicationComponent/xml',
        'xslt' => 'ApplicationComponent/xslt+xml',
        'xsm' => 'ApplicationComponent/vnd.syncml+xml',
        'xspf' => 'ApplicationComponent/xspf+xml',
        'xul' => 'ApplicationComponent/vnd.mozilla.xul+xml',
        'xvm' => 'ApplicationComponent/xv+xml',
        'xvml' => 'ApplicationComponent/xv+xml',
        'xwd' => 'image/x-xwindowdump',
        'xyz' => 'chemical/x-xyz',
        'yaml' => 'text/yaml',
        'yang' => 'ApplicationComponent/yang',
        'yin' => 'ApplicationComponent/yin+xml',
        'yml' => 'text/yaml',
        'zaz' => 'ApplicationComponent/vnd.zzazz.deck+xml',
        'zip' => 'ApplicationComponent/zip',
        'zir' => 'ApplicationComponent/vnd.zul',
        'zirz' => 'ApplicationComponent/vnd.zul',
        'zmm' => 'ApplicationComponent/vnd.handheld-entertainment+xml'
    );

    /**
     * @return string[]
     */
    public static function getMimeTypes(): array
    {
        return self::$extension_to_mime;
    }

    /**
     * Get a mimetype from a filename
     *
     * @param string $filename Filename to generate a mimetype from
     * @return string|null
     */
    public static function guessFromFilename(string $filename)
    {
        return static::guess(pathinfo($filename, PATHINFO_EXTENSION));
    }

    /**
     * Get the mimetype value from a file extension
     *
     * @param string $extension The subject file-extension
     * @return string|null
     */
    public static function guess(string $extension)
    {
        $extension = strtolower($extension);

        return static::$extension_to_mime[$extension] ?? static::MIME_TYPE_IF_UNKNOWN;
    }

    /**
     * @param string $file
     * @param bool $fixed_width
     * @return string
     */
    public static function guessFromFontAwesome(string $file, bool $fixed_width = false)
    {
        $file_mime_type = self::guessFromFile($file);
        $found_icon = 'fa-file-o';

        foreach (self::$font_awesome_to_mime as $mime_type => $icon) {
            if (false !== mb_strpos($file_mime_type, $mime_type)) {
                $found_icon = $icon;
            }
        }

        return 'fa ' . $found_icon . ($fixed_width ? ' fa-fw' : null);
    }

    /**
     * Guesses the mimetype based on a passed (3) file path, (2) {@link \SplFileInfo} instance, or (3)
     *  {@link \SplFileObject} instance. If no mimetype can be guessed, return the value of
     *  {@link static::MIME_TYPE_IF_UNKNOWN}
     *
     * @param string|SplFileInfo|SplFileObject $file
     * @return mixed|string
     */
    public static function guessFromFile(string|SplFileInfo|SplFileObject $file)
    {
        if (is_string($file)) {
            $file = new SplFileInfo($file);
        }

        $extension = mb_strtolower($file->getExtension());

        if ('' === $extension) {
            return static::MIME_TYPE_IF_UNKNOWN;
        }

        if (array_key_exists($extension, static::$extension_to_mime)) {
            return static::$extension_to_mime[$extension];
        }

        if (function_exists('finfo_open') && $file->isFile()) {
            $path = $file->getPath();

            $file_info = finfo_open(FILEINFO_MIME);
            $mime_type = finfo_file($file_info, $path);

            finfo_close($file_info);

            return $mime_type;
        }

        return static::MIME_TYPE_IF_UNKNOWN;
    }

}